require:
  - rubocop-airbnb

Metrics/LineLength:
  Exclude:
    - bin/bundle
    - config/initializers/backtrace_silencers.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/devise.rb
    - db/schema.rb

Airbnb/SimpleModifierConditional:
  Exclude:
    - bin/bundle

Rails/Present:
  Exclude:
    - bin/bundle